### ISSUE TITLE
Causes (Cocoa) Emacs to fail on OS X 10.9 (w/ bash shell when MANPAGE env var is empty)

### ISSUE THREAD

**Issue by RobotDisco** [purcell/exec-path-from-shell#11]
I updated my packages via ELPA and MELPA, so I should have the tcsh-specific fix for this. I'm using bash, though.

<pre>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("" nil 0)
  split-string(nil "")
  exec-path-from-shell-getenvs(("PATH" "MANPATH"))
  exec-path-from-shell-copy-envs(("PATH" "MANPATH"))
  exec-path-from-shell-initialize()
  byte-code("\301\302!\210\303\304!\210\305 \210\306\301\207" [ns-function-modifier prelude-require-packages (exec-path-from-shell) require exec-path-from-shell exec-path-from-shell-initialize hyper] 2)
  require(prelude-osx)
  byte-code("\306\307\"\210\306\307    \"\210\306\307\n\"\210\310\n!\210\311\312\f!\203)\313\314\f\"\210\315\316\317\f\320\321#\"\210\313\322!\210\323\324!\210\323\325!\210\323\326!\210\323\327!\210\323\330!\210\323\331!\210
\332=\203O\323\333!\210\313\334!\210\312%!\203_\316%!\210\335\336&\"'\312&!\203}\313\314&\"\210\315\316\317&\320\321#\"\210\313\337(\"\210\340\341\342\343\344#!\207" [prelude-core-dir prelude-modules-dir prelude-vendor-dir gc-cons-threshold prelude-personal-preload-dir system-type add-to-list load-path prelude-add-subfolders-to-load-path 50000000 file-exists-p message "Loading personal configuration files in %s..." mapc load directory-files t "^[^#].*el$" "Loading Prelude's core..." require prelude-packages prelude-ui prelude-core prelude-mode prelude-editor prelude-global-keybindings darwin prelude-osx "Loading Prelude's modules..." expand-file-name "custom.el" "Prelude is ready to do thy bidding, Master %s!" prelude-eval-after-init run-at-time 5 nil prelude-tip-of-the-day prelude-modules-file prelude-personal-dir custom-file current-user] 6)
  load("/Users/gaelan/.emacs.d/init" t t)
  #[0 "\205\262    \306=\203\307\310Q\202;   \311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
</pre>

**Comment by hiqua** [comment]
I have the same issue regarding the compatibility with tmux autostarting. Is there a way to detect that the shell is run by exec-path-from-shell? Would it be possible to set the variable $INSIDE_EMACS to some non empty string so as to make it detectable?

I already use this to be able to run an interactive shell that won't run tmux within Emacs, since it automatically sets $INSIDE_EMACS (https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html).

**Comment by purcell** [comment]
@hiqua Just don't run an interactive shell from `exec-path-from-shell`. Customize or set `exec-path-from-shell-arguments` to remove `"-i"`.

**Comment by lvh** [comment]
FYI, I seem to be running into this with fish 2.5.0 (not 2.4.0!) and the somewhat regrettably named https://github.com/nvbn/thefuck. If I change either one, the problem goes away.
