### ISSUE TITLE
exec-path paths order reversed

### ISSUE THREAD

**Issue by ghost** [purcell/exec-path-from-shell#15]
I might be missing the point, but couldn't find a solution looking through reported issues.

I'm trying to get pyenv to work transparently in emacs, but it looks like the path order gets reversed when using exec-path-from shell.

In the terminal I will have:

``` bash
$ echo $PATH
/usr/local/opt/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

While when using exec-path-from-shell-initialize, exec-path becomes

``` lisp
("/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/" "/usr/local/opt/pyenv/shims/" "/usr/local/Cellar/emacs/24.3/libexec/emacs/24.\
3/x86_64-apple-darwin13.2.0/")
```

To compare, I evaluated exec-path in non GUI emacs, which shows the the PATH was imported as is:

``` lisp
("/usr/local/opt/pyenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs/24.3/libexec/emacs/24.3/x86_\
64-apple-darwin13.2.0")
```

In GUI emacs, when I run execp-path-from-shell-initialize and eval exec-path manually, PATH seems to be setup correctly as well...

**Comment by Fl1tzi** [comment]
This issue still seems somewhat relevant with path_helper on OS X. What worked for me is making it a non-login shell (removing "-l"). Is there a reason why a login shell is started by default?
