### ISSUE TITLE
Consider removing "-i" from the shell startup args

### ISSUE THREAD

**Issue by purcell** [purcell/exec-path-from-shell#17]
See https://github.com/bbatsov/prelude/issues/625

Might cause breakage if people are setting env vars in files which are only sourced by their shell in interactive mode.

**Comment by braham-snyder** [comment]
Can confirm (more) breakage--the following in my ~/config.fish was freezing Emacs and causing neovim to hog the CPU whenever I attempted to reload my init file from within Emacs (but not on initial start):

```
if status is-interactive
  # $IN_NEOVIM set to "yes" in ~/.vimrc
  # More explicit than $NEOVIM_LISTEN_ADDRESS (that might be a paraphrase):
  # https://github.com/neovim/neovim/issues/3118
  # https://github.com/neovim/neovim/issues/4351
  if test -z $IN_NEOVIM; and test -z $INSIDE_EMACS
    nvim +term
  end
```

Passing `-i` is "user-friendly" in a way, but I don't think there's any reasoning around the fact that it's incorrect--perhaps passing `$INSIDE_EMACS` as well would cover it? Though that seems a little bit hacky.

**Comment by purcell** [comment]
I think that if this change hasn't been made after over 9 years, it's probably not vital. :)
