### ISSUE TITLE
Conflicts with fish-shell

### ISSUE THREAD

**Issue by Nek** [purcell/exec-path-from-shell#21]
The problem is fish-shell uses space as a separator inside PATH env var.
The package can't parse it and in the end exec-path has just one element which is just a copy of PATH env var.

My ad-hoc solution is appending this to my init.el:

    (setq exec-path (split-string (car exec-path)))

**Comment by purcell** [comment]
This is a duplicate of #9, and was confirmed fixed a while ago, so I'm not sure why you're seeing problems. Do you have the latest version of the code?

**Comment by Nek** [comment]
Sorry for the duplicate. I'll check the version.

**Comment by Nek** [comment]
It was outdated. By the way the latest version from marmalade (1.7) gave me the same error. The melpa's version worked fine though.

Thanks for the tip!

**Comment by purcell** [comment]
There's a version on Marmalade? Oh, I should probably update it. There'll always be a stable version on [MELPA Stable](http://stable.melpa.org/), so you can combine Marmalade with MELPA Stable if you like.

**Comment by Nek** [comment]
I've used the one with a date-coded version name. I'll move to the version 1.8.

**Comment by purcell** [comment]
The date-coded version probably came from MELPA originally, then, but the version actually there now will always be up-to-date.
