### ISSUE TITLE
exec-path-from-shell with req-package (use-package)

### ISSUE THREAD

**Issue by usharf** [purcell/exec-path-from-shell#22]
I'm not sure if I should open it here, or at req-package, but thought I should ask if there's any reason why this does not work?

```emacs-lisp
  (req-package exec-path-from-shell                                                                                     
    :if (memq window-system '(mac ns))                                                                                  
    :init                                                                                                               
    (progn                                                                                                              
      (exec-path-from-shell-initialize)                                                                                 
      (exec-path-from-shell-copy-env "ANDROID_HOME"))) 
```

It works fine if I evaluate the expressions manually, but not from init.el, for some reason.
I've tried also without the condition, this block never seem to get evaluated at all.

**Comment by purcell** [comment]
Not sure, sorry. Let's cc @edvorg here and see if he has any idea. @usharf: it will be relevant how you're launching your Emacs, and on which platform, so perhaps you could not that here.

**Comment by edvorg** [comment]
Hi guys. I tried this code:
```elisp
(req-package exec-path-from-shell
  :if (memq window-system '(mac ns))
  :init (progn (print "ok"))
```
It seems ok on my configuration: `os x 10.9, emacs 24.4 cocoa`.
Can you, please, test it without req-package to detect the reason of this issue?
Something like:
```elisp
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns))
  :init (progn (print "ok"))
```
Also I suggest you to check if you are using byte compilation for your configuration files. Maybe you changed your config but, did not recompile it?

**Comment by usharf** [comment]
Well, I don't know what to say... I've been wrestling with this for a couple of hours today, and it didn't work, until now... I didn't change much in my setup, other than switching to terminal for a while. I don't have my configuration byte compiled either. 

Also uninstalled exec-path-from-shell and let req-package re-install automatically.

Sorry guys and thanks.

Using OS X 10.10.1, zsh and emacs-mac (Emacs 24.4.1) from Homebrew.
