### ISSUE TITLE
 execute bash ~/.bashrc or zsh ~/.zshrc

### ISSUE THREAD

**Issue by micanzhang** [purcell/exec-path-from-shell#26]
how execute bash ~/.bashrc or zsh ~/.zshrc in emacs, and copy then to emacs env?

**Comment by purcell** [comment]
Well, you shouldn't do that. Things which affect the environment should be in `.bash_profile` or `.zshenv`.

But with `"-i"` in `exec-path-from-shell-arguments` (the default), then those files should get executed.

**Comment by micanzhang** [comment]
looks like it source ~/.bashrc, actually my default shell is bash, so it's make sense, and j setq exec-path-from-shell-variables with list, everything done as what i wish, thx purcell!
