### ISSUE TITLE
melpa package not working for emacs 24.5

### ISSUE THREAD

**Issue by useremacs** [purcell/exec-path-from-shell#30]
Hi, I can get this to work by putting the .el file on my path and adding the initialization code to my .emacs as suggested in the comments at the top of the file.  but when I use list-packages to list and install the package using elpa, installation goes smoothly, but then it doesn't seem to change the path/exec-path, so am not sure it is activated at all.  thanks for a great package... E

**Comment by purcell** [comment]
Even if you've installed the package using `list-packages`, you'll still have to call `exec-path-from-shell-initialize` or similar for it to take effect.

**Comment by useremacs** [comment]
thanks!  apologies for being slow to understand this; so if I put in my
.emacs file:
(load
"~/.emacs.d/elpa/exec-path-from-shell-1.7/exec-path-from-shell-autoloads.el")
(exec-path-from-shell-initialize)

everything works fine.  but it seems strange to need to do this, as when
the version number changes I would need to change .emacs.  I have auctex
installed as an elpa package and just having it there in the elpa directory
seems all that's needed to install it.  what am I getting wrong?  cheers

**Comment by purcell** [comment]
Right, that `(load ...)` call certainly shouldn't be necessary. The autoloads will be loaded for you when `package-initialize` is called, so you might like to call that explicitly before your other start-up code. Once that is done, it should be enough to call `(exec-path-from-shell-initialize)`. :-)

**Comment by useremacs** [comment]
Hello, thanks so much!  that worked.  Perhaps it would be good to mention
this in the comments at the top of the file...  anyway, appreciate this,
cheers
