### ISSUE TITLE
After (exec-path-from-shell-variables "UNSET_VARIABLE"), (getenv "UNSET_VARIABLE") returns "" rather than nil

### ISSUE THREAD

**Issue by conleym** [purcell/exec-path-from-shell#31]
My expectation is that environment variables that are not set in the shell would not be set in emacs, even if they're explicitly included in the args to `exec-path-from-shell-variables`.

Nine times out of ten this won't matter, but this causes problems with, e.g., `awscli`. I usually set `AWS_PROFILE` to switch accounts, though I sometimes instead use `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (this could vary, e.g., based on the machine on which I'm running, but really I'd just prefer not to have to edit both my emacs init and `.profile`). The various AWS utilties and libraries all react badly to this, ignoring `AWS_PROFILE` if the other two variables are set to "".

I _think_ one solution to this is to do something like `${VAR:+"undefined"}` when printing instead of `${VAR-}` and filtering "undefined" out of the results in `exec-path-from-shell-getenvs`, but I don't really know what I'm talking about :smile:

**Comment by purcell** [comment]
Yep, I can see that working, as long as `/usr/bin/printf` supports that syntax. But of course `"undefined"` isn't particularly safe as a default string. We'd probably need to use something much more improbable.

**Comment by conleym** [comment]
Yeah, `"undefined"` wouldn't be good enough by itself. I was thinking a `defcustom` with some reasonable default value would do the trick.

But it looks like `printf` doesn't understand this syntax :disappointed:, so this may be academic.

**Comment by purcell** [comment]
Hey Mike, I recalled the implementation wrong: `printf` doesn't actually need to support the syntax, just the shell itself. So please see if the latest version of `exec-path-from-shell` (as of b044923) does what you want, and feel free to reopen this issue if not. Thanks for your help with this.

**Comment by conleym** [comment]
Great. Thanks!

There's still a smaller problem here. It doesn't affect me, so I won't reopen the issue, but I figured you should be aware of it. If I do `FOOBAR=""` in my profile, then load up emacs, I get the following:

```
(getenv "FOOBAR")
nil
```

I would ordinarily expect `""` instead. This is why I proposed `${VAR+somethingundefined}` in the first place (though I've not been able to get it to work locally). And, like I said, it's not a problem for me, so I'll leave it to you to decide whether or not it's a bug :smile:. Happy to help if you decide it is, and equally happy to have my issue fixed if not. Thanks again.

**Comment by purcell** [comment]
Ah yes, the shell docs say:

```
       ${parameter:-word}
              Use  Default  Values.   If parameter is unset or null, the expansion of word is substituted.
              Otherwise, the value of parameter is substituted.
```
and similar for `:+`, so the shell doesn't distinguish between `""` and unset. Not sure what the best behaviour is, given this fact. Possibly the new one.

**Comment by conleym** [comment]
You're right. I misread the (open group standard)http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02, from which someone made this handy image:

![sh substitution reference](https://cloud.githubusercontent.com/assets/293492/10265310/48d9b3ac-69fa-11e5-813e-0ef798c35b60.png).

It looks like the most correct thing is to use `${parameter-word}` rather than `${parameter:-word}`. The `+` variations aren't actually helpful at all. Doesn't work properly for me when I make the changes locally, but I might just be doing it wrong.

Either way, I think the current behavior is better than the previous behavior in general. I certainly prefer it.

**Comment by purcell** [comment]
That does actually seem to work, as far as I can tell: if you have any problems with the *new* new version, let me know. :-)

**Comment by conleym** [comment]
:+1:
 
Perfect.
