### ISSUE TITLE
support emacs daemon from launchd

### ISSUE THREAD

**Issue by xiaoxinghu** [purcell/exec-path-from-shell#35]
It works perfectly for GUI emacs. Is it possible to support emacs daemon that launched from `~/Library/LaunchAgents/homebrew.mxcl.emacs.plist`?

**Comment by purcell** [comment]
I'm surprised that it doesn't just work already. What configuration do you have in your emacs startup file for `exec-path-from-shell`?

**Comment by xiaoxinghu** [comment]
I am using [spacemacs](https://github.com/syl20bnr/spacemacs) here. The only config I can find is [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L445-L448).

**Comment by purcell** [comment]
Right. This is really a `spacemacs` issue, I believe.

**Comment by bradJM** [comment]
I had this problem without Spacemacs. It looks like `window-system` is nil when the Emacs daemon starts, which makes sense. Changing my configuration to:

    (when (memq window-system '(mac ns nil))
      (exec-path-from-shell-initialize))

from:

    (when (memq window-system '(mac ns))
      (exec-path-from-shell-initialize))`

resolved it. Apologies for the comment on a closed issue, this is one of the first results I found while looking into the problem so it's likely others may land here.

**Comment by ryukinix** [comment]
I have the same problem using daemon. Why this is really closed?
