### ISSUE TITLE
Speed issue with exec-path-from-shell-initialize

### ISSUE THREAD

**Issue by jwintz** [purcell/exec-path-from-shell#36]
Hello Steve,

First of all, many thanks for this excellent package. However, I realize that is slows down my startup time significantly. I have benchmarked using [benchmark-init](https://github.com/dholm/benchmark-init-el) and here is what I've got.

![screen shot 2015-11-30 at 19 53 05](https://cloud.githubusercontent.com/assets/3277054/11481209/5622c29a-979c-11e5-9d3f-b07c1ba28f9e.png)

On the top is the loading time per `require` call, on the bottom is the contents of the `prolusion-eshell` file that uses `exec-path-from-shell-initialize`. It is 6 times as long as loading my theme.

Is there any way I can speed it up ? Maybe with an autoload at least to defer its loading time when I open an `eshell` ?

Thanks !

**Comment by purcell** [comment]
Yep, no surprise -- it involves running external programs and gathering their input. That will always be slower than running quite a lot of elisp directly inside Emacs.

To speed it up, you can do 3 things:

- Streamline your shell startup files
- Don't call `exec-path-from-shell-initialize` and `exec-path-from-shell-copy-env` separately: instead, add `CMAKE_PREFIX_PATH` to `exec-path-from-shell-variables` and *then* just run `exec-path-from-shell-initialize`.
- Remove `-i` from `exec-path-from-shell-arguments`, if your shell startup files are correctly structured, ie. they do not set any variables in interactive-shell-only files like `.bashrc` or `.zshrc`.

**Comment by purcell** [comment]
(With your current config, there will be 4 shell commands run -- by following the latter 2 tips, you'll cut that down to 1.)

**Comment by jwintz** [comment]
Thanks Steve !
