### ISSUE TITLE
Supoort xonsh

### ISSUE THREAD

**Issue by mrapogee** [purcell/exec-path-from-shell#46]
Could support be added for xonsh?  It would be fine, but xonsh is written in python and therfore doesn't support null bytes.

**Comment by purcell** [comment]
`fish` is nonstandard, and it is supported in `exec-path-from-shell` by asking it to execute `/bin/sh`... perhaps that approach would work for `xonsh` too. I'm happy to consider patches, but I'm not going to work on it myself, sorry.
