### ISSUE TITLE
How to test if an environment variable exists? 

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [purcell/exec-path-from-shell#47]
Hi guys,

I want to know how to test if an environment variable exists and I only want to "copy" it when it exists. I want this is because I need to work on several computers and they have slightly different environment variables set. 

Thanks.

**Comment by purcell** [comment]
Well, if you copy a variable which isn't set, then the value in Emacs will be nil, so I'm not sure what you want. Can you give an example of what outcome you're looking for, and how the current result is different from what you want?
