### ISSUE TITLE
Env variable not copied

### ISSUE THREAD

**Issue by dgellow** [purcell/exec-path-from-shell#54]
Hello,

I have a `.profile`, sourced from my `.zshrc`. 
In `.profile` I export a value for `GOPATH`

```
export GOPATH="$HOME/Development/Go/gopath/"
```

Running `exec-path-from-shell-copy-env` in emacs doesn't seem to work

```
(exec-path-from-shell-copy-env "GOPATH)
(getenv "GOPATH") ;; => nil
```

Am I doing something wrong?

**Comment by purcell** [comment]
`.zshrc` is only sourced for interactive shells, so it might be getting skipped due to your particular `exec-path-from-shell-arguments`.

You should put environment variable settings like that in your `.zshenv`, or in a file which you source from there.

**Comment by dgellow** [comment]
Same issue :s

**Comment by purcell** [comment]
Okay, so perhaps Emacs doesn't think that your shell is `zsh`... what's the result of `M-: (getenv "SHELL")`?

**Comment by dgellow** [comment]
@purcell Correct! The `SHELL` variable was set to "/bin/bash".
I've `setenv`ed it to "/bin/zsh" and everything work as expected.
Thank you for your help 🙇🏻

**Comment by purcell** [comment]
Happy to help. Glad you figured it out.
