### ISSUE TITLE
Expected printf but got blep

### ISSUE THREAD

**Issue by howdoicomputer** [purcell/exec-path-from-shell#56]
```
Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: ""
Warning (initialization): An error occurred while loading ‘/home/howdoicomputer/.emacs.d/init.el’:

error: Expected printf output from shell, but got: ""

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Sad faces.

**Comment by howdoicomputer** [comment]
Also, it looks like this is totally not `exec-path-from-shell`'s fault. I downgraded my version of Fish and the problem went away.

**Comment by jonathanchu** [comment]
Confirmed I had the same issue too (Fish v2.5.0).  I downgraded Fish to v2.4.0 and this issue went away.

**Comment by lvh** [comment]
Same issue. I have reported it in the linked ticket.

**Comment by lvh** [comment]
@jonathanchu @howdoicomputer Do you use `thefuck`?

**Comment by howdoicomputer** [comment]
WHAT DID YOU JUST SAY???

And, yes, yes I do.

**Comment by purcell** [comment]
I don't think there's anything for me to do here, sorry, so I'll go ahead and close this. :-)
