### ISSUE TITLE
Compatibility issue with fish 2.5

### ISSUE THREAD

**Issue by iamthad** [purcell/exec-path-from-shell#57]
As reported in a [spacemacs issue thread](https://github.com/syl20bnr/spacemacs/issues/4755#issuecomment-277375043), there is an issue with the latest version of fish, resulting in the message:

    Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: ""

**Comment by lvh** [comment]
A different issue for this has already been opened and closed:

https://github.com/purcell/exec-path-from-shell/issues/56

It is almost certainly not an exec-path-from-shell bug.  See https://github.com/fish-shell/fish-shell/issues/3809#issuecomment-277400905 for details and https://github.com/syl20bnr/spacemacs/issues/4755#issuecomment-277452286 for a specific remedy if you're using `thefuck`.

**Comment by purcell** [comment]
Yep, duplicate of #56.

**Comment by iamthad** [comment]
My apologies for the dupe.
