### ISSUE TITLE
Make SHELL configurable?

### ISSUE THREAD

**Issue by bennofs** [purcell/exec-path-from-shell#59]
I have my system set up such that I can use both `bash` and `fish`, with `SHELL` being set to `fish` since I use that by default. `exec-path-from-shell` seems to have some issues with fish though, so I would like to override the shell used by `exec-path-from-shell`. Can we add a variable to specify an explicit override?

**Comment by purcell** [comment]
Done, thanks Benno. See the comments in 9def990 .
