### ISSUE TITLE
does not work with bashdb installed

### ISSUE THREAD

**Issue by sdague** [purcell/exec-path-from-shell#61]
For long and largely silly reasons, I had previously installed bashdb on my laptop (a step debugger for bash... yes there really were reasons). When I tried to get exec-path-from-shell working on that machine I kept getting issues during the initialize about a bad bash ioctl.

Uninstalling bashdb fixed it. But it seemed worth reporting that there is an incompatibility with that.

Ubuntu 16.10, x86_64, all the latest patches.

**Comment by purcell** [comment]
Thanks! This issue will hopefully allow people to google the problem in future, but I'll go ahead and close it because I don't think there's anything to be done on the `exec-path-from-shell` side.
