### ISSUE TITLE
Support dired-do-shell-command 

### ISSUE THREAD

**Issue by QiangF** [purcell/exec-path-from-shell#64]
When the program is on a custom path, dired-do-shell-command can't find it. dired-do-shell-command must have been using another path setting.

**Comment by purcell** [comment]
Please provide steps to reproduce.

Following the code for that command, it ultimately uses `shell-file-name` to run the file, e.g. `/bin/bash -c /your/script/path`, so it should work the same as anything else.

**Comment by QiangF** [comment]
I am using the emacs window manager EXWM. The problem disappears when I reboot the system. I guess "/bin/bash -c " doesn't reload the .bashrc file each time. Thank you for looking into this issue!

**Comment by purcell** [comment]
> I guess "/bin/bash -c " doesn't reload the .bashrc file each time

Correct: it only loads that file for interactive shells, or when called with "-i".
