### ISSUE TITLE
Not working with --daemon

### ISSUE THREAD

**Issue by kirkins** [purcell/exec-path-from-shell#69]
I've installed via MELPA then restarted.

When I open a GUI instance, then `eshell `, `echo $PATH`, I ended up with the same path from my bash as expected.

But when I open emacs from terminal connecting to an existing daemon instance then repeat the same process the path isn't that used in bash.

**Comment by purcell** [comment]
Did you follow the instructions? Installing is not sufficient: there's an additional required step noted in the README. (Just like all the built-in Emacs packages, installation of packages from MELPA etc. does not imply that the user want them all activated, even if "activated" had a well-defined meaning.)
