### ISSUE TITLE
Shell variables other than 'path' are not copied even though the exec-path-from-shell-variables contains them

### ISSUE THREAD

**Issue by parhamdoustdar** [purcell/exec-path-from-shell#72]
I have modified the `exec-path-from-shell-variables` variable to contain two other variables, `GOROOT` and `GOPATH`. Here is what I get when I describe the variable:

```
exec-path-from-shell-variables is a variable defined in ‘exec-path-from-shell.el’.
Its value is ("PATH" "MANPATH" "GOPATH" "GOROOT")
Original value was ("PATH" "MANPATH")
```

However, when I run `M-x getenv RET GOPATH RET` and the same with `GOROOT`, they are not set.

What am I doing wrong?

Thanks a lot for the awesome library! <3

**Comment by purcell** [comment]
Hi! How did you set that variable? Did you call `exec-from-path-initialize` _after_ setting it? Customising the variable is not enough to ensure this happens.

**Comment by parhamdoustdar** [comment]
Hi,
Ah, alright. I didn’t know that. I manually set the variable just before calling `exec-path-from-shell-initialize` and now it works!
Thanks a lot for the quick help! <#

**Comment by purcell** [comment]
Cool, happy to help.
