### ISSUE TITLE
Source a shell script 

### ISSUE THREAD

**Issue by CeleritasCelery** [purcell/exec-path-from-shell#83]
At my company the envivroment comes from sourcing some shell scripts. For a multitude of reasons I don’t want to source these files in my login shell. Is there a way to have exec-path-from-shell to run a command (I.e. to source those files) before it loads the environment?

**Comment by purcell** [comment]
Not directly.

However, you could set `exec-path-from-shell-shell-name` to a shell script which sets that environment, and then `exec`s your regular shell in that modified environment with the args it was passed.
