### ISSUE TITLE
Is it still necessary to enable exec-path-from-shell under Linux?

### ISSUE THREAD

**Issue by re-mx** [purcell/exec-path-from-shell#86]
Hello:

Is it still necessary to enable this package on Linux now?
The premise is the latest Emacs version and popular distributions/shells/system configurations/Emacs distributions.

Thank you.

**Comment by purcell** [comment]
It depends, but sometimes yes, I believe.

**Comment by purcell** [comment]
(Ultimately users will need to make their own decisions about when it's necessary. Generally enabling the package too often is not a bad thing in terms of correctness, it just slows down startup slightly.)

**Comment by azzamsa** [comment]
Yes, I've tried to not use exec-path package. some packages can't find the executable. 

It adds some startup time. but I try to embrace it. we don't restart Emacs too often, right.
